# Change these first
owner: dein-github-username
repo: uptime-monitor # Muss exakt matchen mit deinem Repo-Namen

sites:
  - name: Henneth SFTP
    url: https://sftp.henneth.de
  - name: Henneth Photos
    url: https://photos.henneth.de
  - name: Henneth Sync
    url: https://sync.henneth.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # cname: demo.upptime.js.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Henneth System Status
  introTitle: "**Henneth Prod** Status Overview"
  introMessage: Echtzeit-Monitoring der Infrastruktur.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Setup scheduled runs (every 5 minutes)
# Default is every 5 minutes
user-agent: upptime
